# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
import torch
x = torch.rand(7, 7)
print(x)



tensor([[0.0601, 0.9474, 0.2132, 0.5053, 0.3207, 0.0938, 0.6302],
        [0.1150, 0.7018, 0.0600, 0.6573, 0.2319, 0.5907, 0.8936],
        [0.0051, 0.3522, 0.7697, 0.3387, 0.6477, 0.7603, 0.1750],
        [0.3069, 0.9367, 0.4898, 0.2720, 0.2744, 0.1880, 0.4325],
        [0.4714, 0.0906, 0.8681, 0.7658, 0.2277, 0.8415, 0.0227],
        [0.5125, 0.8997, 0.8942, 0.1879, 0.6823, 0.6403, 0.9278],
        [0.6200, 0.1251, 0.8891, 0.1856, 0.4621, 0.0188, 0.0831]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:

y = torch.rand(1, 7)

y_t = y.T  

result = torch.matmul(x, y_t)

print("Shape of x:", x.shape)
print("Shape of y_t:", y_t.shape)
print("Result shape:", result.shape)
print(result)


Shape of x: torch.Size([7, 7])
Shape of y_t: torch.Size([7, 1])
Result shape: torch.Size([7, 1])
tensor([[0.6102],
        [0.7746],
        [0.6343],
        [0.4570],
        [0.4778],
        [0.9291],
        [0.3631]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
import torch

torch.manual_seed(0)

x = torch.rand(7, 7)

y = torch.rand(1, 7)

y_t = y.t()

result = torch.matmul(x, y_t)

print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [13]:

torch.manual_seed(0)

if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [14]:

torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

tensor_a = torch.rand(2, 3, device=device)
tensor_b = torch.rand(2, 3, device=device)

print(tensor_a, tensor_b)



Device: cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [15]:

torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)
tensor_a = torch.rand(2, 3, device=device)
tensor_b = torch.rand(2, 3, device=device)
result = torch.matmul(tensor_a, tensor_b.T)

print(result, result.shape)


Device: cuda
tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [16]:
max_val = result.max()
min_val = result.min()

print("Maximum value:", max_val)
print("Minimum value:", min_val)



Maximum value: tensor(0.7668, device='cuda:0')
Minimum value: tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
max_index = torch.argmax(result)
min_index = torch.argmin(result)

print("Max index:", max_index)
print("Min index:", min_index)


Max index: tensor(1, device='cuda:0')
Min index: tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
torch.manual_seed(7)
tensor_a = torch.rand(1, 1, 1, 10)
tensor_b = tensor_a.squeeze()

print(tensor_a, tensor_a.shape)
print(tensor_b, tensor_b.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
